// Builds src/ into js/, which Nextcloud serves as-is. The built files are
// committed so the app installs by copying the folder, with no build step.
import { readFileSync } from 'node:fs';
import { defineConfig, type Plugin } from 'vite';

/**
 * Writes js/THIRD-PARTY.md, listing every package the bundle contains with its
 * version and licence, taken from what was actually bundled so it can't drift.
 */
function thirdParty(): Plugin {
  return {
    name: 'third-party-notice',
    generateBundle(_options, bundle) {
      const packages = new Set<string>();
      for (const output of Object.values(bundle)) {
        if (output.type !== 'chunk') continue;
        for (const id of Object.keys(output.modules)) {
          const match = id.match(/node_modules\/((?:@[^/]+\/)?[^/]+)/);
          if (match) packages.add(match[1]);
        }
      }
      const rows = [...packages].sort().map((name) => {
        const meta = JSON.parse(readFileSync(`node_modules/${name}/package.json`, 'utf8'));
        return `| ${name} | ${meta.version} | ${meta.license} |`;
      });
      this.emitFile({
        type: 'asset',
        fileName: 'THIRD-PARTY.md',
        source: '# Third-party code in these files\n\nGenerated by the build from the packages it bundled.\n\n'
          + '| Package | Version | Licence |\n|---|---|---|\n' + rows.join('\n') + '\n',
      });
    },
  };
}

export default defineConfig({
  define: { 'process.env.NODE_ENV': JSON.stringify('production') },
  plugins: [thirdParty()],
  build: {
    outDir: 'js',
    emptyOutDir: true,
    sourcemap: false,
    target: 'es2022',
    lib: {
      // main: the sphere view, on Files, Photos and Memories pages.
      // admin: the settings page.
      entry: { main: 'src/main.ts', admin: 'src/admin.ts' },
      formats: ['es'],
      fileName: (_format, name) => `golblick-${name}.mjs`,
    },
    rollupOptions: {
      output: { chunkFileNames: '[name]-[hash].chunk.mjs' },
    },
  },
});
